<?php

function speakers(){
    return [
        'hsu' => [
            'name'    => '徐德航',
            'company' => 'ijoing (愛就贏)',
            'title'   => '總經理',
            'bio'     => '愛就贏總經理徐德航在遊戲業界資歷十年，曾任上海遊戲新幹線市場部主任、遊戲新幹線香港辦公室主任、智冠台北研發中心企劃部主任與智冠市場投資處主任。在長期接觸台灣獨立遊戲開發者後發現，遊戲大賣很難提前預測，擴散效應必須掌握天時地利與人和很難複製。因此愛就贏綜合創業育成、共同開發、遊戲營運、發行平台等，與上架的公司專案合作，共同創作遊戲，成為遊戲開發商的共同開發夥伴及產品共同擁有者',
            'pic'     => 'hsu.jpg',
        ],
        'ian' => [
            'name'    => 'Ian Liao (廖聰哲)',
            'company' => 'Golface',
            'title'   => '創辦人',
            'bio'     => '現為 Golface (綠夾克運動有限公司) 負責人，發現高爾夫球在台灣是很昂貴的運動，很多人希望透過這個運動建立人際關係，但國內高球場經營非常傳統，缺一套球場專屬物流系統，於是喜愛打高爾夫球的 Ian 看到這個需求，和團隊成員開發出高爾夫球場的數位化解決方案 Golface，從動態球道空拍攝影、即時資訊回報、便捷賽事紀錄管理，甚至包括球友間的社交平台都提供專項服務。目前 Golface已把整套解決方案，導入 Rolex 全球排名1000 大的高爾夫球場',
            'pic'     => 'ian_500.jpg',
        ],
        'mhung' => [
            'name'    => 'Michael Hung (洪志鵬)',
            'company' => 'Mozilla Taiwan',
            'title'   => '行銷總監',
            'bio'     => '洪志鵬 (Michael Hung)，別名 Michaelsoft。現職為 Mozilla 台灣分公司資深行銷總監，曾任台灣微軟全球技術支援中心副總經理、昇陽電腦(Sun Microsystems) 行銷總監等職。亦曾為專職作家，著有《最後的江湖道義》等四本書',
            'pic'     => 'Michael_Hung_500.jpg',
        ],
        'keynes' => [
            'name'    => 'Keynes (鄭鎧尹)',
            'company' => 'iKala',
            'title'   => '設計總監',
            'bio'     => '鄭鎧尹博士為 LIVEhouse.in/iKala 共同創辦人, 並擔任產品設計總監一職，負責產品設計及產品策略。LIVEhouse.in 為第一個國產直播平台；iKala為國內最大唱歌社群。其研究領域為人機互動介面設計, 並曾於日本最頂尖的 UI 研究所 JST ERATO 及微軟亞洲研究院從事研究。其在閒暇時間喜愛撰寫科技或設計相關文章, 在 MMDays 或 UIUI 粉絲團上可追蹤到他的動態。',
            'pic'     => 'keynes.jpg',
        ],
        'mark' => [
            'name'    => '宋牧奇',
            'company' => 'BISTRO & Zillians',
            'title'   => '創辦人',
            'bio'     => '宋牧奇是 Zillians Inc. (奇群科技) 執行長，致力於發展 GPU 為基礎的雲端運算平台。自交通大學畢業後，在高效能運算領域深入耕耘，曾在 IBM 加州聖荷西研究中心貢獻超級電腦的檔案系統設計，而在 2008 年創辦了奇群科技，打造了世界最強大的線上遊戲平台和通用 GPU 叢集環境。2014 年以創立子公司 42ARK，運用 GPU 開發具備貓臉辨識功能的智慧型餵食產品 Bistro',
            'pic'     => 'mark.jpg',
        ],
        'tico' => [
            'name'    => 'Tico Wu',
            'company' => 'Tyche',
            'title'   => '創辦人',
            'bio'     => 'Tico 為堤刻科技創辦人，經營一個年輕的 Mobile App 開發團隊，成立約半年，便在 Apple AppStore 上擁有數個自行開發 App，並也為知名企業及國家單位進行 App 的開發或合作，透過與異業結盟或合作的方式，將原有的商業模式加值或吸引原來沒有的使用者加入，創造對使用者更便利的資訊環境',
            'pic'     => 'tico.jpg',
        ],
        'sleepnova' => [
            'name'    => 'sleepnova (周立瑋)',
            'company' => '呼叫小黃',
            'title'   => '創辦人',
            'bio'     => '周立瑋為頑皮工坊 (Sleepnova, Inc.) 創辦人，帶領團隊提供全方位數位解決方案，包括網頁前後端和移動裝置整合，相信運用簡單的界面、實用的科技，提供便利大家的生活，就是對社會的回饋的最佳方式。代表性專案為呼叫小黃、愛料理、東森新聞 App 等等',
            'pic'     => 'sleepnova.jpg',
        ],
        'ernest' => [
            'name'    => 'Ernest Chiang',
            'company' => 'PAFERS',
            'title'   => '共同創辦人',
            'bio'     => '小時候玩 MS-DOS, OS/2, Windows 3.1,  Slackware，玩著玩著玩到大學申請少了零點多分沒法進資工系玩，改玩半導體製程和微小機電，幸運地進入台積研究所玩製程整合從研發、試產玩到量產。熱愛開放與不務正業的精神，曾經玩網路創業，現在上班在玩傳統產業 + 軟硬體整合，試著把無線通訊塞進健身器材中。下班參與 Mozilla 台灣社群 MozTW SUMO 專案，以及支援朋友們玩各種創業。夢想與大家玩出各種可能性。愛台灣，不解釋',
            'pic'     => 'Ernest_profile_high_500.jpg',
        ],
        'asuscloud' => [
            'name'    => 'ASUS Cloud 邀請神秘嘉賓',
            'company' => 'ASUS Cloud',
            'title'   => '神秘嘉賓',
            'bio'     => '就說是神秘嘉賓了，當然很神秘',
            'pic'     => 'asus-cloud_tmp.png',
        ],
        'microsoft' => [
            'name'    => 'Microsoft 邀請神秘嘉賓',
            'company' => 'Microsoft',
            'title'   => '神秘嘉賓',
            'bio'     => '就說是神秘嘉賓了，當然很神秘',
            'pic'     => 'msft_tmp.gif',
        ],
        'amazon' => [
            'name'    => 'Amazon 邀請神秘嘉賓',
            'company' => 'Amazon',
            'title'   => '神秘嘉賓',
            'bio'     => '就說是神秘嘉賓了，當然很神秘',
            'pic'     => 'aws.png',
        ],
        'yahoo' => [
            'name'    => 'Yahoo 邀請神秘嘉賓',
            'company' => 'Yahoo',
            'title'   => '神秘嘉賓',
            'bio'     => '就說是神秘嘉賓了，當然很神秘',
            'pic'     => 'yahoo_tmp.jpg',
        ],
        'ibm' => [
            'name'    => '何志恒',
            'company' => 'IBM',
            'title'   => 'IBM全球行動企業方案首席架構師',
            'bio'     => 'IBM全球行動企業方案首席架構師 <等待講者回覆喔>',
            'pic'     => 'ibm_tmp.png',
        ],
        'drake' => [
            'name'    => 'Drake (官順暉)',
            'company' => 'KKBOX',
            'title'   => 'Sr. Principal Engineer',
            'bio'     => '於電腦動畫產業服務期間，組織了一隻台灣動畫產業的研發團隊，發表了國際論文，參與制作了得獎動畫，成了 Pixar 軟體與技術的專家。還意外自經濟部獲頒青年創新希望獎，更不小心參與了 PyCon Taiwan 籌備委員之一。今年起，投入影音串流這個新戰場，以提供台灣一個值得擁有的影音串流服務為目標邁進。',
            'pic'     => 'KKBOX_drake_guan.jpg',
        ],        
        'tp' => [
            'name'    => 'Tzu-ping Chung',
            'company' => 'BIMEtek Co. Ltd.',
            'title'   => 'Software Architect',
            'bio'     => 'TP is a professional software engineer who builds his career around open source software, and enjoys committing back his little efforts to help make the community better. He writes C++ for a living, builds MacDown, an open source Markdown editor, with Objective-C, and hosts many websites built with Python.',
            'pic'     => 'generic_speaker.png',
        ],        
        'atsushi' => [
            'name'    => 'Atsushi Enomoto',
            'company' => 'Xamarin Inc.',
            'title'   => 'Software Engineer',
            'bio'     => 'Japanese Xamarin.Android developer, and the Mono project developer who mostly worked on class libraries.',
            'pic'     => 'generic_speaker.png',
        ],        
        'peter' => [
            'name'    => 'Peter Tseng',
            'company' => 'Newegg Taiwan, Inc.',
            'title'   => 'Software Engineer',
            'bio'     => '大學、研究所、博士班全都在台灣科技大學資訊工程系，主修Machine Learning和Data Mining，但博班念了2年就當兵去了。現職為Newegg Taiwan, Inc.的小小軟體工程師，主要負責的工作內容為Adaptive Product Matching。喜愛打羽球，程度(自認為是乙組的)中上。小時候愛看卡通，尤其是GUNDAM 系列，老想著要把打球專用的ZERO system做出來，好讓自己能在打球時稱王(笑)',
            'pic'     => 'generic_speaker.png',
        ],        
        'kewang' => [
            'name'    => 'kewang',
            'company' => '三竹資訊',
            'title'   => '研發主任',
            'bio'     => '研發替代役役畢之後，到了三竹資訊專職Android App的開發，2013年公司因為要成立雲端部門開發產品，就被一腳踢到雲上面。 現在則是在雲上面專職於後端開發，包括NoSQL以及AP的連接，AP以及前端的RESTful API串接。 喜歡玩各種先進的前後端技術，包括Java、Node.js、AngularJS......等。',
            'pic'     => 'generic_speaker.png',
        ],        
        'joe' => [
            'name'    => 'Joe',
            'company' => 'Tainan.py',
            'title'   => 'Organizer',
            'bio'     => '魯蛇喬，後端工程師，現為居住於台南的創業連續失敗家。每個月與 MOSUT 社群舉辦 Tainan.py 聚會推廣另其醉心而優雅的程式語言： Python。',
            'pic'     => 'generic_speaker.png',
        ],        
        'peni' => [
            'name'    => 'Peni',
            'company' => 'CyberLink',
            'title'   => '工程師',
            'bio'     => '一個每天上班都在寫iOS/Android的工程師，骨子裡愛的是Windows Phone，因為市集上的App太少，開始了自行開發上架之路，希望能貢獻一己之力，讓Windows Phone App的選擇能越來越多。代表作是天氣App《晴時多雲偶陣雨》。',
            'pic'     => 'generic_speaker.png',
        ],        
    ];
}
