<?php

function speakers(){
    return [
        'hsu' => [
            'name'    => '徐德航',
            'company' => 'ijoing (愛就贏)',
            'title'   => '總經理',
            'bio'     => '愛就贏總經理徐德航在遊戲業界資歷十年，曾任上海遊戲新幹線市場部主任、遊戲新幹線香港辦公室主任、智冠台北研發中心企劃部主任與智冠市場投資處主任。在長期接觸台灣獨立遊戲開發者後發現，遊戲大賣很難提前預測，擴散效應必須掌握天時地利與人和很難複製。因此愛就贏綜合創業育成、共同開發、遊戲營運、發行平台等，與上架的公司專案合作，共同創作遊戲，成為遊戲開發商的共同開發夥伴及產品共同擁有者',
            'pic'     => 'hsu.jpg',
        ],
        'ian' => [
            'name'    => 'Ian Liao (廖聰哲)',
            'company' => 'Golface',
            'title'   => '創辦人',
            'bio'     => '現為 Golface (綠夾克運動有限公司) 負責人，發現高爾夫球在台灣是很昂貴的運動，很多人希望透過這個運動建立人際關係，但國內高球場經營非常傳統，缺一套球場專屬物流系統，於是喜愛打高爾夫球的 Ian 看到這個需求，和團隊成員開發出高爾夫球場的數位化解決方案 Golface，從動態球道空拍攝影、即時資訊回報、便捷賽事紀錄管理，甚至包括球友間的社交平台都提供專項服務。目前 Golface已把整套解決方案，導入 Rolex 全球排名1000 大的高爾夫球場',
            'pic'     => 'ian_500.jpg',
        ],
        'mhung' => [
            'name'    => 'Michael Hung (洪志鵬)',
            'company' => 'Mozilla Taiwan',
            'title'   => '資深行銷總監',
            'bio'     => '洪志鵬 (Michael Hung)，別名 Michaelsoft。現職為 Mozilla 台灣分公司資深行銷總監，曾任台灣微軟全球技術支援中心副總經理、昇陽電腦(Sun Microsystems) 行銷總監等職。亦曾為專職作家，著有《最後的江湖道義》等四本書',
            'pic'     => 'Michael_Hung_500.jpg',
        ],
        'keynes' => [
            'name'    => 'Keynes (鄭鎧尹)',
            'company' => 'iKala',
            'title'   => '設計總監',
            'bio'     => '鄭鎧尹博士為 LIVEhouse.in/iKala 共同創辦人, 並擔任產品設計總監一職，負責產品設計及產品策略。LIVEhouse.in 為第一個國產直播平台；iKala為國內最大唱歌社群。其研究領域為人機互動介面設計, 並曾於日本最頂尖的 UI 研究所 JST ERATO 及微軟亞洲研究院從事研究。其在閒暇時間喜愛撰寫科技或設計相關文章, 在 MMDays 或 UIUI 粉絲團上可追蹤到他的動態。',
            'pic'     => 'keynes.jpg',
        ],
        'mark' => [
            'name'    => '宋牧奇',
            'company' => 'BISTRO & Zillians',
            'title'   => '創辦人',
            'bio'     => '宋牧奇是 Zillians Inc. (奇群科技) 執行長，致力於發展 GPU 為基礎的雲端運算平台。自交通大學畢業後，在高效能運算領域深入耕耘，曾在 IBM 加州聖荷西研究中心貢獻超級電腦的檔案系統設計，而在 2008 年創辦了奇群科技，打造了世界最強大的線上遊戲平台和通用 GPU 叢集環境。2014 年以創立子公司 42ARK，運用 GPU 開發具備貓臉辨識功能的智慧型餵食產品 Bistro',
            'pic'     => 'mark.jpg',
        ],
        'tico' => [
            'name'    => 'Tico Wu',
            'company' => 'Tyche',
            'title'   => '創辦人',
            'bio'     => 'Tico 為堤刻科技創辦人，經營一個年輕的 Mobile App 開發團隊，成立約半年，便在 Apple AppStore 上擁有數個自行開發 App，並也為知名企業及國家單位進行 App 的開發或合作，透過與異業結盟或合作的方式，將原有的商業模式加值或吸引原來沒有的使用者加入，創造對使用者更便利的資訊環境',
            'pic'     => 'tico.jpg',
        ],
        'sleepnova' => [
            'name'    => 'sleepnova (周立瑋)',
            'company' => '呼叫小黃',
            'title'   => '創辦人',
            'bio'     => '周立瑋為頑皮工坊 (Sleepnova, Inc.) 創辦人，帶領團隊提供全方位數位解決方案，包括網頁前後端和移動裝置整合，相信運用簡單的界面、實用的科技，提供便利大家的生活，就是對社會的回饋的最佳方式。代表性專案為呼叫小黃、愛料理、東森新聞 App 等等',
            'pic'     => 'sleepnova.jpg',
        ],
        'ernest' => [
            'name'    => 'Ernest Chiang',
            'company' => 'PAFERS Tech',
            'title'   => 'Technology Integration',
            'bio'     => '小時候玩 MS-DOS, OS/2, Windows 3.1,  Slackware，玩著玩著玩到大學申請少了零點多分沒法進資工系玩，改玩半導體製程和微小機電，幸運地進入台積研究所玩製程整合從研發、試產玩到量產。熱愛開放與不務正業的精神，曾經玩網路創業，現在上班在玩傳統產業 + 軟硬體整合，試著把無線通訊塞進健身器材中。下班參與 Mozilla 台灣社群 MozTW SUMO 專案，以及支援朋友們玩各種創業。夢想與大家玩出各種可能性。愛台灣，不解釋',
            'pic'     => 'Ernest_profile_high_500.jpg',
        ],
        'asuscloud' => [
            'name'    => 'ASUS Cloud 邀請神秘嘉賓',
            'company' => 'ASUS Cloud',
            'title'   => '神秘嘉賓',
            'bio'     => '就說是神秘嘉賓了，當然很神秘',
            'pic'     => 'asus-cloud_tmp.png',
        ],
        'ericsk' => [
            'name'    => '上官林傑 (ericsk)',
            'company' => 'Microsoft',
            'title'   => '應用開發技術經理',
            'bio'     => '網路代號 ericsk，曾在中華電信從事網站以及 App 的開發工作，亦曾組織 Taipei GTUG 社群，並且積極參與台灣各種社群，熱愛軟體開發技術，特別在 web、cloud、mobile 領域有所涉獵，現任台灣微軟的應用技術開發經理 (Technical Evangelist)，持續與開發者社群互動。
講題標語: 快速、可靠、穩定的應用程式',
            'pic'     => 'msft_tmp.gif',
        ],
        'wangtun' => [
            'name'    => 'Wang-Tun Chou (周旺暾)',
            'company' => 'Microsoft',
            'title'   => '雲端平台事業部副總經理',
            'bio'     => '目前主要工作在推動微軟伺服器及雲端平台策略與行銷。曾任台灣微軟創新中心營運負責人、蕃薯藤數位科技協理。',
            'pic'     => 'msft_tmp.gif',
        ],
        'amazon' => [
            'name'    => 'Amazon 邀請神秘嘉賓',
            'company' => 'Amazon',
            'title'   => '神秘嘉賓',
            'bio'     => '就說是神秘嘉賓了，當然很神秘',
            'pic'     => 'aws.png',
        ],
        'yahoo' => [
            'name'    => 'Yahoo 邀請神秘嘉賓',
            'company' => 'Yahoo',
            'title'   => '神秘嘉賓',
            'bio'     => '就說是神秘嘉賓了，當然很神秘',
            'pic'     => 'yahoo_tmp.jpg',
        ],
        'ibm' => [
            'name'    => '何志恒',
            'company' => 'IBM',
            'title'   => 'IBM全球行動企業方案首席架構師',
            'bio'     => 'IBM全球行動企業方案首席架構師 <等待講者回覆喔>',
            'pic'     => 'ibm_tmp.png',
        ],
        'synology' => [
            'name'    => '曾貴熙 Hunter Tseng & 楊智焙 Chih-Pei Yang',
            'company' => 'Synology 群暉科技',
            'title'   => '神秘嘉賓',
            'bio'     => '<等待講者回覆喔>',
            'pic'     => 'synology_dark_bg.png',
        ],
        'john' => [
            'name'    => '謝耀輝(John Sie)',
            'company' => 'ACCUPASS',
            'title'   => '營運長 Chief Operating Officer',
            'bio'     => '謝耀輝(John Sie) 畢業 於台北工專電子及台灣科大資管， 曾任鴻海軟體工程師及PM，2009年創辦Accuvally Inc. 任CTO；於2011年推出「活動通 Accupass」榮獲國內外諸多大獎，該年榮獲《經理人雜誌》選為 100大 MVP專業經理人； 2012年轉任COO於大陸開展「活動行」服務，2013年公司獲得國際創投上億投資投資，成為亞太地區最具規模活動平台。',
            'pic'     => 'John.jpg',
        ],
        'drake' => [
            'name'    => 'Drake (官順暉)',
            'company' => 'KKBOX',
            'title'   => 'Sr. Principal Engineer',
            'bio'     => '於電腦動畫產業服務期間，組織了一隻台灣動畫產業的研發團隊，發表了國際論文，參與制作了得獎動畫，成了 Pixar 軟體與技術的專家。還意外自經濟部獲頒青年創新希望獎，更不小心參與了 PyCon Taiwan 籌備委員之一。今年起，投入影音串流這個新戰場，以提供台灣一個值得擁有的影音串流服務為目標邁進。',
            'pic'     => 'KKBOX_drake_guan.jpg',
        ],        
        'tp' => [
            'name'    => 'Tzu-ping Chung',
            'company' => 'BIMEtek Co. Ltd.',
            'title'   => 'Software Architect',
            'bio'     => 'TP is a professional software engineer who builds his career around open source software, and enjoys committing back his little efforts to help make the community better. He writes C++ for a living, builds MacDown, an open source Markdown editor, with Objective-C, and hosts many websites built with Python.',
            'pic'     => 'generic_speaker.png',
        ],        
        'atsushi' => [
            'name'    => 'Atsushi Enomoto',
            'company' => 'Xamarin Inc.',
            'title'   => 'Software Engineer',
            'bio'     => 'Japanese Xamarin.Android developer, and the Mono project developer who mostly worked on class libraries.',
            'pic'     => 'generic_speaker.png',
        ],        
        'peter' => [
            'name'    => 'Peter Tseng',
            'company' => 'Newegg Taiwan, Inc.',
            'title'   => 'Software Engineer',
            'bio'     => '大學、研究所、博士班全都在台灣科技大學資訊工程系，主修Machine Learning和Data Mining，但博班念了2年就當兵去了。現職為Newegg Taiwan, Inc.的小小軟體工程師，主要負責的工作內容為Adaptive Product Matching。喜愛打羽球，程度(自認為是乙組的)中上。小時候愛看卡通，尤其是GUNDAM 系列，老想著要把打球專用的ZERO system做出來，好讓自己能在打球時稱王(笑)',
            'pic'     => 'generic_speaker.png',
        ],        
        'kewang' => [
            'name'    => 'kewang',
            'company' => '三竹資訊',
            'title'   => '研發主任',
            'bio'     => '研發替代役役畢之後，到了三竹資訊專職Android App的開發，2013年公司因為要成立雲端部門開發產品，就被一腳踢到雲上面。 現在則是在雲上面專職於後端開發，包括NoSQL以及AP的連接，AP以及前端的RESTful API串接。 喜歡玩各種先進的前後端技術，包括Java、Node.js、AngularJS......等。',
            'pic'     => 'generic_speaker.png',
        ],        
        'joe' => [
            'name'    => 'Joe',
            'company' => 'Tainan.py',
            'title'   => 'Organizer',
            'bio'     => '魯蛇喬，後端工程師，現為居住於台南的創業連續失敗家。每個月與 MOSUT 社群舉辦 Tainan.py 聚會推廣另其醉心而優雅的程式語言： Python。',
            'pic'     => 'generic_speaker.png',
        ],        
        'peni' => [
            'name'    => 'Peni',
            'company' => 'CyberLink',
            'title'   => '工程師',
            'bio'     => '一個每天上班都在寫iOS/Android的工程師，骨子裡愛的是Windows Phone，因為市集上的App太少，開始了自行開發上架之路，希望能貢獻一己之力，讓Windows Phone App的選擇能越來越多。代表作是天氣App《晴時多雲偶陣雨》。',
            'pic'     => 'generic_speaker.png',
        ],        
        'ben' => [
            'name'    => 'Ben Lue',
            'company' => 'COIMOTION',
            'title'   => '總架構師',
            'bio'     => '獨立軟體開發者。旅美期間曾在IBM Almaden Research Center, Cognos Inc., NetClue Corp.等公司工作。所創立的 NetClue Corp.為多家公司的收購目標。返台後喜歡自造軟體,目前為 COIMOTION API 服務的總架構師。',
            'pic'     => 'coimotion_tmp.png',
        ],        
        'imsardine' => [
            'name'    => 'imsardine',
            'company' => 'KKBOX',
            'title'   => '工程師',
            'bio'     => '網路代號 imsardine，愛寫程式的魚，目前在 KKBOX 負責自動化測試開發工作。',
            'pic'     => 'KKBOX_jeremy.jpg',
        ],        
        'vincent' => [
            'name'    => 'Vincent Chen',
            'company' => 'KKBOX',
            'title'   => '「KKPLAY」負責人',
            'bio'     => '「KKBOX」旗下遊戲開發團隊「KKPLAY」負責人，有10年唱片產業及10年遊戲產業經驗。',
            'pic'     => 'KKBOX_VincentChen.jpg',
        ],        
        'evillon' => [
            'name'    => '張景隆',
            'company' => '迅行科技',
            'title'   => 'Director of Apps',
            'bio'     => '一個熱愛 iOS 開發、Ruby、Linux 的開發者。 喜愛分享、寫作，以分享知識為樂。 喜歡把問題簡化，用最簡單的方式解決問題。 - 參與 CodeData 作者 iOS Dev Club 講者 Cocoahead Taichung 講者 參加蘋果官方主辦 2013年 Tech Talk 麥克自由聚(Apple, Mac, iOS 相關) 講師 - 近期 iOS Apps 作品 CWMoney 為 台灣AppStore 最受歡迎的記賬軟體，付費排行當中榜上常客，更是台灣財經類App第一名。 biiChat 為 全台第一個電子商務即時通訊軟體，整合電子商務與訊息的便利性。 BTWCar 為 藍牙軟硬整合應用 App。',
            'pic'     => 'generic_speaker.png',
        ],        
        'anistar' => [
            'name'    => 'Anistar 宋志峰',
            'company' => 'Yahoo',
            'title'   => 'EC Mobile Team',
            'bio'     => '長期專注於 Mobile app 開發，其中所開發的 Magic Shutter 被 New York Times 評為 iOS 上前十大最佳攝影軟體，之前曾在恆逸教育訓練中心針對 Mobile、Font-End、Design 領域有多年授課與專案實戰經驗，目前服務於雅虎電子商務部，致力用技術與創意提供有趣的 Mobile 應用。',
            'pic'     => 'anistar.jpg',
        ],        
        'eddie' => [
            'name'    => '高見龍',
            'company' => '五倍紅寶石股份有限公司',
            'title'   => '紅寶石鑑定商',
            'bio'     => '高見龍，兩個小朋友的爸爸。目前靠 Ruby/Rails/iOS app 開發以及研磨紅寶石糊口渡日。',
            'pic'     => 'generic_speaker.png',
        ],        
        'johnny' => [
            'name'    => '宋岡諺 (Johnny Sung)',
            'company' => 'Hiiir(時間軸科技)',
            'title'   => '手機工程師',
            'bio'     => '目前是Hiiir(時間軸科技)的一名小小工程師 主要在於手機端的 iOS / Android 開發，無意間拿到一隻公司的Google glass， 才好好認識什麼叫做「穿戴式」裝置，揭開一連串有趣的應用',
            'pic'     => 'generic_speaker.png',
        ],        
        'jarsing' => [
            'name'    => '陳佳新',
            'company' => '奇步應用',
            'title'   => '技術長',
            'bio'     => '接觸程式設計的年齡跟Tesla電動車老闆馬斯克差不多，都是11、12歲。熱中於投稿電腦雜誌與翻譯電腦書籍，譯作包括歐萊禮的《Programming Android》。在軟體業打滾了7年。於2013年5月與妻子共同創辦奇步應用工作室，專注於APP開發。iOS作品曾於2013年被網路公司收購。Android作品在2014年分別榮獲Samsung Smart App Callenge挑戰賽佳作以及經濟部工業局Open Data創新應用競賽特優。',
            'pic'     => 'generic_speaker.png',
        ],        
        'pichu' => [
            'name'    => 'Pichu Chen',
            'company' => 'Taiwan Intelligent Home / 台灣智慧家庭',
            'title'   => 'CTO',
            'bio'     => 'TIH是個致力於推動台灣家庭自動化以及建立軟體產業鏈的團隊。 藉由主動學習各個智慧家電的通訊方式，並重新放出Open API來達成此一目標。 團隊成員來自中山大學CDPA，是個維護近四千名住宿生網路的學生組織。',
            'pic'     => 'generic_speaker.png',
        ],        
        'ryudoawaru' => [
            'name'    => '鄧慕凡',
            'company' => '五倍紅寶石股份有限公司',
            'title'   => '火云邪神',
            'bio'     => '鄧慕凡, 1997年開始遊戲業十年生涯, 2007年開始網站創業; 除了經營台灣最大車友社群 FSC 以及台灣免費論壇系統 FREEBBS.TW 外，也是五倍紅寶石股份有限公司的共同創辦人; 工作之餘也積極經營Ruby語言社群, 現為台灣 Ruby程式語言社群「Ruby Taiwan」, 年度國際研討會「RubyConf Taiwan」以及Railsgirls Taipei 工作坊的主辦人。',
            'pic'     => 'MuFan.jpg',
        ],        
        'virus' => [
            'name'    => '小璋丸 (吳政璋)',
            'company' => '中華數位科技 Softnext Inc.',
            'title'   => '程序員',
            'bio'     => '我是個小小程序員，本行從事網路安全， 除了寫程式，也愛好長笛和三鐵， 自從陷入三鐵的無窮敗家迴圈後，開始研究相關的行動應用， 目前正在努力整合各種運動與健康的裝置， 希望可以完成一個神祕的計畫。',
            'pic'     => 'generic_speaker.png',
        ],        
        'ant' => [
            'name'    => 'ant',
            'company' => 'MUZIK ONLINE',
            'title'   => '總工程師',
            'bio'     => '目前專注於「合法的安全程式設計」。在「自由/開放源碼」「資訊安全」及「程式設計」領域擁有數場公開及非公開的教育訓練課程和演講，同時撰寫 過數篇發明專利。閒暇時喜歡沉浸在「心理學」及「經濟學」的世界，並時常穿梭於「人性」、「法律」與「科技」的三角關係中。',
            'pic'     => 'generic_speaker.png',
        ],        
        'brian' => [
            'name'    => 'Brian Wang',
            'company' => 'Positive Grid',
            'title'   => 'Development Manager, Mobile Apps',
            'bio'     => '同時具備Maker精神以及對音樂的熱情於一身，Brian堅信行動裝置對未來音樂人有著不可或缺的重要性。從來沒停止過結合音樂科技與行動裝置、開放硬體與雲端服務，做各式各樣的嘗試與開發，將成果實際帶入自己的表演活動中使用，以享受自己的實作成果為樂。在2011年起就與Positive Grid團隊合作，研發出JamUp, BIAS, Final Touch等iOS平台上的專業吉他效果與音樂音訊處理軟體，不僅取得市場上的成功，在美國iTunes Store Music App 熱門付費與利潤排行上持續名列前茅，產品也受到使用者與專業音樂媒體的一致好評，在全世界累計已超過百萬使用者。',
            'pic'     => 'BrianWang.jpg',
        ],        
        'superbil' => [
            'name'    => 'Superbil',
            'company' => 'Eatgo',
            'title'   => '',
            'bio'     => '喜愛 Cocoa 框架的熱血工程師，從事 iOS 開發三年，對於新奇事物充滿好奇心、對於 cocoa 喜歡的原因，最近也開始研究起咖啡來。',
            'pic'     => 'generic_speaker.png',
        ],        
        'elvismetaphor' => [
            'name'    => '林英傑',
            'company' => 'gamania',
            'title'   => 'Senior Software Engineer',
            'bio'     => 'I am a senior Android application developer at Gamania to develop mobile social apps and write unit tests and user acceptance tests to verify the quality of apps. Before working at Gamania, I was a Android application engineer to develop multimedia apps and cloud apps at HTC. I love to join the community activities to study from experienced developers. I also hope to have the opportunity to share my experience with other developers.',
            'pic'     => 'generic_speaker.png',
        ],        
        'tsaikd' => [
            'name'    => '蔡程豐 (tsaikd)',
            'company' => '賽恩倍吉',
            'title'   => '顧問',
            'bio'     => 'Tsai KD，宅宅工程師，熱衷學習各種新技術，從前端到後端都稍有涉獵，除了一些常見的程式語言之外，目前較關注 Go 語言；系統方面，自從 Docker 出現後，就把 VM 當成備胎了...XD 目前待的公司主要營業項目是專利相關業務，對於專利資料的處理有幾年的經驗。',
            'pic'     => 'generic_speaker.png',
        ]        
    ];
}
