export const speaker = '/api/2022/speaker'
export const schedule = '/api/2022/session'
export const tags = '/api/2022/speaker/tags'
export const scheduleUnconf = '/api/2022/unconf'
export const volunteer = 'api/2022/volunteer'
export const sponsor = '/api/2022/sponsor'
